"""Structured run ledger: every experiment/demo appends one JSON line to
logs/runs.jsonl and refreshes logs/LATEST.md.

Purpose: a new Claude/analysis session reads PROJECT_LOG.md plus the tail of
logs/runs.jsonl instead of re-exploring the repo or re-running experiments -
the ledger is the single source of truth for "what was run, with what
parameters, and what came out".

Design rules:
  * append-only JSONL (never rewrite history; one line = one run)
  * never crash the host script - all I/O wrapped
  * compact: floats rounded, only scalar metrics kept

Usage:
    from emv.runlog import RunLogger
    with RunLogger("run_all", note="figures+anim") as rl:
        ...
        rl.finish(metrics={...}, outputs=["out/fig_x.png"])   # optional early
    # on exception the entry is still written with status="error"
"""
import json
import os
import sys
import time
import datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOG_DIR = os.path.join(ROOT, "logs")
LEDGER = os.path.join(LOG_DIR, "runs.jsonl")
LATEST = os.path.join(LOG_DIR, "LATEST.md")


def _round(v, sig=5):
    if isinstance(v, float):
        return float(f"{v:.{sig}g}")
    return v


def _flat_scalars(d, prefix="", out=None):
    out = {} if out is None else out
    if d is None:
        return out
    for k, v in d.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            _flat_scalars(v, key + ".", out)
        elif isinstance(v, (int, float, str, bool)) or v is None:
            out[key] = _round(v)
    return out


class RunLogger:
    def __init__(self, kind: str, note: str = "", params: dict | None = None):
        self.kind = kind
        self.note = note
        self.params = _flat_scalars(params)
        self.t0 = time.time()
        self._entry = None

    # -- context manager -------------------------------------------------
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if self._entry is None:
            if exc_type is None:
                self.finish()
            else:
                self.finish(status=f"error:{exc_type.__name__}",
                            metrics={"message": str(exc)[:200]})
        return False

    # -- main API ---------------------------------------------------------
    def finish(self, metrics: dict | None = None, outputs: list | None = None,
               status: str = "ok", **extra):
        entry = dict(
            ts=datetime.datetime.now().isoformat(timespec="seconds"),
            kind=self.kind,
            status=status,
            wall_s=_round(time.time() - self.t0, 4),
            argv=" ".join(sys.argv[1:])[:200],
            note=self.note,
        )
        if self.params:
            entry["params"] = self.params
        if metrics:
            entry["metrics"] = _flat_scalars(metrics)
        if outputs:
            entry["outputs"] = [os.path.relpath(o, ROOT).replace("\\", "/")
                                if os.path.isabs(o) else o for o in outputs]
        entry.update(extra)
        self._entry = entry
        _append(entry)
        return entry


def log_run(kind: str, note: str = "", params: dict | None = None,
            metrics: dict | None = None, outputs: list | None = None,
            status: str = "ok", **extra):
    """One-shot logging (no timing)."""
    rl = RunLogger(kind, note=note, params=params)
    rl.t0 = time.time()
    return rl.finish(metrics=metrics, outputs=outputs, status=status, **extra)


# ----------------------------------------------------------------------
def _append(entry: dict):
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
        with open(LEDGER, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, separators=(",", ":")) + "\n")
        _rewrite_latest()
    except Exception as e:                                    # never crash host
        print(f"[runlog] logging failed: {e}", file=sys.stderr)


def read_ledger(n: int | None = None) -> list[dict]:
    try:
        with open(LEDGER, encoding="utf-8") as fh:
            lines = [json.loads(l) for l in fh if l.strip()]
        return lines[-n:] if n else lines
    except FileNotFoundError:
        return []


def _rewrite_latest(n: int = 14):
    runs = read_ledger()
    lines = [
        "# Latest runs (auto-generated by emv/runlog.py - do not edit)",
        "",
        f"Ledger: `logs/runs.jsonl` ({len(runs)} entries). Newest first.",
        "",
        "| when | kind | status | wall | key numbers | note |",
        "|---|---|---|---|---|---|",
    ]
    for r in reversed(runs[-n:]):
        m = r.get("metrics", {})
        keys = list(m)[:4]
        nums = "; ".join(f"{k}={m[k]}" for k in keys) or "-"
        lines.append(f"| {r['ts']} | {r['kind']} | {r['status']} | "
                     f"{r.get('wall_s', 0):.0f}s | {nums} | {r.get('note', '')} |")
    lines += ["", "Full state of the project: read `PROJECT_LOG.md` at repo root."]
    with open(LATEST, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
